CREATE TABLE IF NOT EXISTS teams (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    start DATETIME NOT NULL,
    end DATETIME NOT NULL,
    project VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);
